name: SSHX Public Terminal

on:
  workflow_dispatch:   # manual trigger

jobs:
  sshx-job:
    runs-on: ubuntu-latest
    steps:
      - name: Change hostname
        run: |
          sudo hostnamectl set-hostname ash
          echo "127.0.0.1 ash" | sudo tee -a /etc/hosts

      - name: Install curl
        run: sudo apt update && sudo apt install -y curl

      - name: Run sshx
        run: |
          curl -sSf https://sshx.io/get | sh -s run
